#!/usr/bin/env bash
# openllm-self-sha256: 2d46ece0e7e4f198b0796e81a83d49c52d91f07aca049d4d802cee50ad37d37f
# Generated by @openllm/registry. Edit the registry source, not this artifact.
set -euo pipefail

# The ENTIRE program — runtime, embedded assets, authored body — lives inside
# this one function, invoked on the file's last line. Bash parses a function
# body completely before executing anything, so a truncated `curl | bash`
# stream is a syntax error at ANY cut point and NOTHING runs.
_openllm_main() {

_openllm_fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
_openllm_has_command() { command -v "$1" >/dev/null 2>&1; }

_openllm_sha256_file() {
  if _openllm_has_command shasum; then shasum -a 256 "$1" | cut -d' ' -f1
  elif _openllm_has_command sha256sum; then sha256sum "$1" | cut -d' ' -f1
  else _openllm_fail "shasum or sha256sum is required"; fi
}

_openllm_verify_self() {
  local source expected canonical actual count
  source="${BASH_SOURCE[0]:-}"
  # Piped (curl | bash): no file to re-read, so the byte self-check cannot run.
  # Integrity there = the immutable commit-pinned URL + the whole-script parse
  # guard (_openllm_main wraps everything, so a truncated download is a syntax
  # error and NOTHING executes). A real file gets the full check. Export an
  # EMPTY digest so `set -u` consumers (record_install_stamp) stay defined —
  # the stamp helper skips on a non-64-hex value, so piped installs simply
  # leave no drift stamp.
  if [ -z "$source" ] || [ ! -f "$source" ]; then
    readonly OPENLLM_SELF_SHA256=""
    export OPENLLM_SELF_SHA256
    return 0
  fi
  count="$(grep -c '^# openllm-self-sha256: ' "$source" || true)"
  [ "$count" = "1" ] || _openllm_fail "installer checksum field is invalid"
  expected="$(sed -n 's/^# openllm-self-sha256: \([0-9a-f]\{64\}\)$/\1/p' "$source")"
  [ "${#expected}" = "64" ] || _openllm_fail "installer checksum is invalid"
  umask 077
  canonical="$(mktemp "${TMPDIR:-/tmp}/openllm-self.XXXXXX")" || _openllm_fail "cannot create checksum file"
  trap 'rm -f "$canonical"' RETURN
  sed 's/^# openllm-self-sha256: [0-9a-f]\{64\}$/# openllm-self-sha256: __OPENLLM_SELF_SHA256__/' "$source" > "$canonical"
  actual="$(_openllm_sha256_file "$canonical")"
  [ "$actual" = "$expected" ] || _openllm_fail "installer checksum mismatch"
  rm -f "$canonical"
  trap - RETURN
  readonly OPENLLM_SELF_SHA256="$expected"
  export OPENLLM_SELF_SHA256
}

_openllm_verify_self

has_command() { command -v "$1" >/dev/null 2>&1; }
ensure_dir() { mkdir -p "$1"; }
copy_file() { [ -f "$1" ] && cp "$1" "$2"; }

sed_inplace() {
  local pattern="$1" replacement="$2" file="$3"
  if sed --version 2>/dev/null | grep -q GNU; then sed -i "s|${pattern}|${replacement}|g" "$file"
  else sed -i '' "s|${pattern}|${replacement}|g" "$file"; fi
}

safe_rmrf() {
  local target="$1" parent="$2"
  case "$target" in ""|"/"|"$HOME") _openllm_fail "refusing to remove $target" ;; esac
  case "/$target/" in *"/../"*) _openllm_fail "refusing path containing .." ;; esac
  case "$target" in "$parent"/*) ;; *) _openllm_fail "$target escapes $parent" ;; esac
  rm -rf "$target"
}

backup_once() {
  local src="$1" root="$HOME/.openllm/backups/$2" rel dest
  case "$src" in "$HOME"/*) rel="${src#"$HOME"/}" ;; *) rel="${src#/}" ;; esac
  dest="$root/$rel"
  [ ! -e "$dest" ] && [ ! -e "$dest.absent" ] || return 0
  (umask 077; mkdir -p "$(dirname "$dest")") 2>/dev/null || return 0
  if [ -f "$src" ]; then cp -p "$src" "$dest" 2>/dev/null && chmod 600 "$dest" 2>/dev/null || true
  else : > "$dest.absent" 2>/dev/null || true; fi
  chmod 700 "$HOME/.openllm/backups" "$root" 2>/dev/null || true
}

ensure_cli() {
  local display="$1" cmd="$2" dest_bin="$3" install_url="$4"
  if has_command "$cmd" || [ -x "$dest_bin" ]; then printf '  %s: already installed.\n' "$display"; return 0; fi
  if [ -n "${OPENLLM_SKIP_CLI_INSTALL:-}" ]; then
    printf '  %s: CLI not installed. Run its official installer first.\n' "$display" >&2
    return 1
  fi
  printf '  %s: installing the official CLI...\n' "$display"
  curl -fsSL "$install_url" | bash
  has_command "$cmd" || [ -x "$dest_bin" ] || _openllm_fail "$display install completed but its CLI was not found"
}

# ── Install state: ONE canonical file, ~/.openllm/state.json ────────────────
# Line-oriented JSON we fully own (only this runtime writes it): the opening
# and closing braces on their own lines and EXACTLY one entry per line —
#   "setup-<slug>": {"sha256":"…","version":"…","commit":"…"},
# so bash can update it with grep/sed alone (no jq/python3 dependency).
# Written IN PLACE (cat >), not tmp+rename: under the daemon's OS sandbox
# state.json is a FILE-scoped grant — a sibling tmp create + rename needs
# create-rights on the (ungranted) ~/.openllm dir. The next content is staged
# in $TMPDIR first and restored on a failed write, so a mid-write failure
# never truncates the record (same posture as the settings.json merges).
OPENLLM_STATE_FILE="$HOME/.openllm/state.json"

_openllm_state_entry_line() {
  grep -m1 "^\"setup-codex\":" "$OPENLLM_STATE_FILE" 2>/dev/null || true
}

_openllm_state_field() {
  # $1 = field name; prints the entry's field value (empty when absent).
  _openllm_state_entry_line | sed -n "s/.*\"$1\":\"\([^\"]*\)\".*/\1/p"
}

_openllm_state_rewrite() {
  # $1 = replacement entry line ('' = delete). Rebuilds the file from the
  # surviving entry lines + the replacement, brace-wrapped. Best-effort: any
  # failure leaves the previous state intact and never fails the caller.
  local tmp orig
  tmp="$(mktemp "${TMPDIR:-/tmp}/openllm-state.XXXXXX" 2>/dev/null)" || return 0
  {
    printf '{\n'
    { grep '^"' "$OPENLLM_STATE_FILE" 2>/dev/null || true; } | grep -v "^\"setup-codex\":" || true
    [ -n "$1" ] && printf '%s\n' "$1"
    printf '}\n'
  } > "$tmp" 2>/dev/null || { rm -f "$tmp" 2>/dev/null; return 0; }
  orig="$(mktemp "${TMPDIR:-/tmp}/openllm-state-orig.XXXXXX" 2>/dev/null)" || { rm -f "$tmp" 2>/dev/null; return 0; }
  cat "$OPENLLM_STATE_FILE" > "$orig" 2>/dev/null || true
  if ! { cat "$tmp" > "$OPENLLM_STATE_FILE"; } 2>/dev/null; then
    cat "$orig" > "$OPENLLM_STATE_FILE" 2>/dev/null || true
  fi
  chmod 600 "$OPENLLM_STATE_FILE" 2>/dev/null || true
  rm -f "$tmp" "$orig" 2>/dev/null || true
}

record_install_stamp() {
  # Piped installs export an empty digest (no file to self-hash) — skip the
  # stamp rather than writing a value drift comparison would misread.
  [[ "${OPENLLM_SELF_SHA256:-}" =~ ^[0-9a-f]{64}$ ]] || return 0
  (umask 077; mkdir -p "$HOME/.openllm") 2>/dev/null || return 0
  local commit=""
  [[ "${OPENLLM_REGISTRY_COMMIT:-}" =~ ^[0-9a-f]{40}$ ]] && commit="$OPENLLM_REGISTRY_COMMIT"
  _openllm_state_rewrite "\"setup-codex\": {\"sha256\":\"$OPENLLM_SELF_SHA256\",\"version\":\"1.7.1\",\"commit\":\"$commit\",\"gateway\":\"${OPENLLM_GATEWAY_MODE:-}\"},"
  # Legacy per-file stamps superseded by state.json — clear so nothing stale
  # survives beside the canonical record.
  rm -f "$HOME/.openllm/installed/setup-codex" \
    "$HOME/.openllm/installed/setup-codex.version" \
    "$HOME/.openllm/installed/setup-codex.commit" 2>/dev/null || true
  rmdir "$HOME/.openllm/installed" 2>/dev/null || true
}
clear_install_stamp() {
  _openllm_state_rewrite ""
  # Also clear legacy stamp files: the per-file installed/ era, tar-era route
  # prefixes ("setups-"/"plugins-"), and the pre-fold "plugin"-area name.
  rm -f "$HOME/.openllm/installed/setup-codex" \
    "$HOME/.openllm/installed/setup-codex.version" \
    "$HOME/.openllm/installed/setup-codex.commit" \
    "$HOME/.openllm/installed/setups-codex" \
    "$HOME/.openllm/installed/plugin-codex" \
    "$HOME/.openllm/installed/plugins-codex" 2>/dev/null || true
  rmdir "$HOME/.openllm/installed" 2>/dev/null || true
}
read_install_stamp() {
  local value
  value="$(_openllm_state_field sha256)"
  # Legacy fallback: the per-file installed/ era (pre-state.json installs).
  if [ -z "$value" ]; then
    local candidate
    for candidate in "setup-codex" "setups-codex" "plugin-codex" "plugins-codex"; do
      [ -f "$HOME/.openllm/installed/$candidate" ] || continue
      value="$(cat "$HOME/.openllm/installed/$candidate" 2>/dev/null || true)"
      break
    done
  fi
  [[ "$value" =~ ^[0-9a-f]{64}$ ]] && printf '%s' "$value"
  return 0
}
read_install_version() {
  local value
  value="$(_openllm_state_field version)"
  [ -n "$value" ] || value="$(cat "$HOME/.openllm/installed/setup-codex.version" 2>/dev/null || true)"
  case "$value" in *[!0-9a-zA-Z.-]*|'') return 0 ;; esac
  printf '%s' "$value"
}
read_install_gateway() {
  # The gateway mode this item was INSTALLED with ("local"/"cloud"); empty
  # for stamps predating the field (pre-gateway-mode installs).
  local value
  value="$(_openllm_state_field gateway)"
  case "$value" in local|cloud) printf '%s' "$value" ;; esac
  return 0
}
emit_install_state() {
  # $1 = "true"/"false" (the script's own installed verdict). Prints the
  # complete `-s` state JSON line from the wrapper-owned stamp readers —
  # ONE format string, so the contract the daemon's parseState reads can't
  # drift per script.
  local version="null" gateway="null" iv igw
  iv="$(read_install_version)"
  [ -n "$iv" ] && version="\"$iv\""
  igw="$(read_install_gateway)"
  [ -n "$igw" ] && gateway="\"$igw\""
  printf '{"installed":%s,"version":%s,"installed_sha256":"%s","installed_commit":"%s","gateway":%s}\n' \
    "$1" "$version" "$(read_install_stamp)" "$(read_install_commit)" "$gateway"
}
read_install_commit() {
  local value
  value="$(_openllm_state_field commit)"
  [ -n "$value" ] || value="$(cat "$HOME/.openllm/installed/setup-codex.commit" 2>/dev/null || true)"
  [[ "$value" =~ ^[0-9a-f]{40}$ ]] || return 0
  printf '%s' "$value"
}

OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-}"
GATEWAY_ORIGIN="$OPENLLM_CLOUD_ORIGIN"
API_KEY="${OPENLLM_API_KEY:-}"
OPENLLM_REGISTRY_REQUIRES_KEY="1"

_openllm_prepare_mode() {
  local mode="install" arg
  for arg in "$@"; do
    case "$arg" in
      -u) mode="uninstall" ;;
      -s) mode="state" ;;
    esac
  done
  if [ "$mode" = "install" ]; then
    [ -n "$OPENLLM_CLOUD_ORIGIN" ] || _openllm_fail "OPENLLM_CLOUD_ORIGIN is required"
    if [ "$OPENLLM_REGISTRY_REQUIRES_KEY" = "1" ]; then
      [ -n "$API_KEY" ] || _openllm_fail "OPENLLM_API_KEY is required"
    fi
  fi
}
# Install-time gateway mode (local | cloud, default local — "local first").
# Parsed and STRIPPED here so authored script bodies keep their strict
# usage loops; the value reaches them as OPENLLM_GATEWAY_MODE. A client
# setup bakes the daemon base URL under "local" and the cloud origin under
# "cloud"; the mode is stamped so the dashboard can prompt a reinstall
# when the user flips it. Only setups declaring `gateway_modes` accept the
# flag (compiled in as the capability gate below) — passing it to any
# other setup fails rather than stamping a meaningless mode.
OPENLLM_REGISTRY_GATEWAY_CAPABLE="1"
OPENLLM_GATEWAY_MODE="${OPENLLM_GATEWAY_MODE:-local}"
_openllm_gw_args=()
while [ $# -gt 0 ]; do
  case "$1" in
    --gateway|--gateway=*)
      [ "$OPENLLM_REGISTRY_GATEWAY_CAPABLE" = "1" ] || _openllm_fail "this setup does not take --gateway (no gateway_modes declared)"
      case "$1" in
        --gateway)
          shift
          [ $# -gt 0 ] || _openllm_fail "--gateway requires a value (local|cloud)"
          OPENLLM_GATEWAY_MODE="$1" ;;
        *)
          OPENLLM_GATEWAY_MODE="${1#--gateway=}" ;;
      esac
      shift ;;
    *)
      _openllm_gw_args+=("$1"); shift ;;
  esac
done
case "$OPENLLM_GATEWAY_MODE" in
  local|cloud) ;;
  *) _openllm_fail "invalid --gateway value (expected local or cloud)" ;;
esac
# Non-gateway setups export EMPTY so record_install_stamp never stamps a
# meaningless mode and `-s` reports gateway:null.
[ "$OPENLLM_REGISTRY_GATEWAY_CAPABLE" = "1" ] || OPENLLM_GATEWAY_MODE=""
export OPENLLM_GATEWAY_MODE
set -- ${_openllm_gw_args[@]+"${_openllm_gw_args[@]}"}

# Resolve the base URL the setup bakes (gateway-capable setups, INSTALL
# runs only — a `-s`/`-u` run must not pay a network probe). ONE shared
# implementation so probe policy (port default, timeout, messages) can't
# drift across scripts. "local" probes the daemon's loopback /status for
# REACHABILITY only and falls back to the cloud origin with a warning;
# "cloud" always uses the origin. Exported for authored bodies.
OPENLLM_API_BASE="${OPENLLM_CLOUD_ORIGIN:-}"
_openllm_is_install=1
for _openllm_arg in "$@"; do
  case "$_openllm_arg" in -u|-s) _openllm_is_install=0 ;; esac
done
if [ "$OPENLLM_REGISTRY_GATEWAY_CAPABLE" = "1" ] && [ "$_openllm_is_install" = "1" ] && [ "$OPENLLM_GATEWAY_MODE" = "local" ]; then
  _openllm_daemon_port="${OPENLLM_DAEMON_PORT:-8787}"
  if curl -fsS --max-time 2 "http://127.0.0.1:${_openllm_daemon_port}/status" >/dev/null 2>&1; then
    OPENLLM_API_BASE="http://127.0.0.1:${_openllm_daemon_port}"
    echo "Local daemon detected — using http://127.0.0.1:${_openllm_daemon_port} as the API base (local gateway mode)."
  else
    echo "Warning: local gateway mode requested but no daemon is reachable — using the cloud origin. Re-run this setup after starting the daemon."
  fi
fi
export OPENLLM_API_BASE

_openllm_prepare_mode "$@"

materialize_registry_assets() { :; }

# Configure the Codex CLI to route through OpenLLM — unified install / uninstall
# / state.
#
#   (no flag)  install: ensure the CLI + merge our managed regions into config.toml
#   -u         uninstall: strip the `# >>> openllm … <<<` managed regions + catalog
#   -s         state: print one JSON line {"installed":bool,"version":string|null}
#
# Run via `bash <file>` by the setup wrapper, which exports `$OPENLLM_CLOUD_ORIGIN` /
# `$API_KEY` and the `ensure_cli` / `ensure_dir` / `has_command` helpers. do_state
# is self-contained (no key, no inherited helpers).

CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
CONFIG_FILE="$CODEX_DIR/config.toml"
MODELS_FILE="$CODEX_DIR/openllm-models.json"

do_install() {
  # Ensure the Codex CLI is present before configuring it: reuse the existing
  # install if any, else run the official installer. (The daemon's isolated CLI is
  # just a symlink to this same binary — one install path, the non-isolated one.)
  ensure_cli "Codex" codex \
    "$HOME/.local/bin/codex" \
    "https://chatgpt.com/codex/install.sh"

  ensure_dir "$CODEX_DIR"

  # No custom header to inject: the local daemon authenticates with the SAME
  # `sk-llm` key Codex carries, and the gateway detects a live daemon from that
  # key's server-side activity — so it 307s subscription (chatgpt) hops to THIS
  # machine's daemon with no client header. See
  # `docs/proposals/daemon-control-via-neon-longpoll.md`.

  # Base URL comes from the assembler wrapper's shared gateway resolution
  # ($OPENLLM_API_BASE — local daemon when --gateway local and one is
  # reachable, else the cloud origin). See registryShellRuntime.

  # Fetch a Codex model catalog generated from YOUR activated models (fallback
  # chains like `ultra`/`plus` + every connected provider model), keyed by slug
  # with real context-window metadata. Without it Codex can't find metadata for
  # our alias / non-OpenAI slugs and warns "Model metadata for <slug> not found.
  # Defaulting to fallback metadata; this can degrade performance and cause
  # issues" — then auto-compacts against a wrong 272k window. Authenticated with
  # your API key so it reflects your own chains. Best-effort: if the fetch fails
  # we skip the `model_catalog_json` line so the config stays valid (re-run to
  # pick it up).
  local catalog_line=""
  if curl -fsS -H "Authorization: Bearer ${API_KEY}" \
       "${OPENLLM_CLOUD_ORIGIN}/api/setup/codex/model-catalog" -o "$MODELS_FILE.tmp" 2>/dev/null; then
    mv "$MODELS_FILE.tmp" "$MODELS_FILE"
    catalog_line="model_catalog_json = \"${MODELS_FILE}\"
"
  else
    rm -f "$MODELS_FILE.tmp"
  fi

  # TOML requires top-level keys BEFORE any [table], so the provider-selection
  # keys and the provider table are two separate marked regions: the selection
  # is prepended (stays above every table), the table is appended.
  local TOP_BLOCK="# >>> openllm (managed) >>>
model_provider = \"openllm\"
model = \"ultra\"
${catalog_line}# <<< openllm (managed) <<<
"
  local TABLE_BLOCK="# >>> openllm provider (managed) >>>
[model_providers.openllm]
name = \"OpenLLM\"
base_url = \"${OPENLLM_API_BASE}/v1\"
wire_api = \"responses\"
experimental_bearer_token = \"${API_KEY}\"
# <<< openllm provider (managed) <<<
"

  # Idempotent + TOML-safe merge. Strip any prior openllm-managed regions AND the
  # user's existing top-level model_provider/model (those before the first
  # [table]) so we never create duplicate keys; then PREPEND our selection block
  # and APPEND our provider table, preserving everything else.
  local cleaned
  # Write-once original backup (durable, kept forever) — distinct from the
  # per-run .openllm-bak rollback aid below, which is overwritten each install.
  if type backup_once >/dev/null 2>&1; then backup_once "$CONFIG_FILE" "setup/codex"; fi
  if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.openllm-bak"
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      /^[[:space:]]*\[/ { seen_table=1 }
      seen_table==0 && $0 ~ /^[[:space:]]*(model_provider|model)[[:space:]]*=/ { next }
      { print }
    ' "$CONFIG_FILE")
  else
    cleaned=""
  fi
  {
    printf '%s' "$TOP_BLOCK"
    [ -n "$cleaned" ] && printf '%s\n' "$cleaned"
    printf '%s' "$TABLE_BLOCK"
  } > "$CONFIG_FILE"

  echo "Codex configured."
  echo "  Provider: openllm → ${OPENLLM_API_BASE}/v1 (wire_api=responses)"
  echo "  Config:   $CONFIG_FILE"
  echo "  Model:    ultra (default fallback chain)"
  echo "            Override per run with: codex -m <model>  (e.g. anthropic/claude-opus-4-8)"
  echo "            Codex's in-app /model picker only lists OpenAI models — use -m or edit"
  echo "            'model =' above to reach any OpenLLM catalog id / chain alias."
  if [ -n "$catalog_line" ]; then
    echo "  Catalog:  $MODELS_FILE (model_catalog_json — silences 'metadata not found')"
  else
    echo "  Catalog:  not fetched — Codex may warn 'model metadata not found'; re-run to add it."
  fi
  echo "  Daemon:   the chatgpt subscription runs on your local daemon —"
  echo "            start it + connect; the gateway routes to it via your API key."
}

do_uninstall() {
  # Best-effort + idempotent: strips the `# >>> openllm … <<<` managed regions
  # install wrote (the selection keys + the [model_providers.openllm] table) and
  # removes the fetched model catalog, leaving every other config.toml line
  # intact. No-op when the config is absent.
  if [ -f "$CONFIG_FILE" ]; then
    # Same region markers install emits — drop every openllm-managed block.
    local cleaned
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      { print }
    ' "$CONFIG_FILE")
    # Atomic replace: write to a temp file then mv over the config, so an
    # interrupted write can't corrupt/truncate config.toml.
    local tmp
    tmp=$(mktemp)
    if printf '%s\n' "$cleaned" > "$tmp" && mv "$tmp" "$CONFIG_FILE"; then
      echo "  Removed OpenLLM managed regions from $CONFIG_FILE"
    else
      rm -f "$tmp"
      echo "  Warning: failed to update $CONFIG_FILE — left untouched." >&2
      return 1
    fi
  else
    echo "  No config.toml found — nothing to undo."
  fi

  if [ -f "$MODELS_FILE" ]; then
    rm -f "$MODELS_FILE"
    echo "  Removed model catalog: $MODELS_FILE"
  fi

  echo "Codex OpenLLM configuration removed."
}

# Print one JSON line describing install state. Installed ⇔ our managed region
# marker is present in config.toml (the durable signal install writes). Exit 0
# always; the JSON IS the payload. No key, no network. (The `diverged` flag is
# injected by the gateway's state wrapper from the install-time version stamp.)
do_state() {
  local installed="false"
  if [ -f "$CONFIG_FILE" ] && grep -q "^# >>> openllm" "$CONFIG_FILE" 2>/dev/null; then
    installed="true"
  fi
  version="null"
  iv="$(read_install_version)"
  [ -n "$iv" ] && version="\"$iv\""
  emit_install_state "$installed"
}

MODE="install"
while [ $# -gt 0 ]; do
  case "$1" in
    -u) MODE="uninstall"; shift ;;
    -s) MODE="state"; shift ;;
    *) echo "usage: install.sh [-u|-s]" >&2; exit 2 ;;
  esac
done

case "$MODE" in
  install)   do_install; record_install_stamp ;;
  uninstall) do_uninstall; clear_install_stamp ;;
  state)     do_state ;;
esac
}
_openllm_main "$@"
