#!/usr/bin/env bash
# openllm-self-sha256: 5e126beb624baab14a9c24365a1f9d029bcb01970e93f719c40756f82e8a0af7
# Generated by @openllm/registry. Edit the registry source, not this artifact.
set -euo pipefail

_openllm_fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
_openllm_has_command() { command -v "$1" >/dev/null 2>&1; }

_openllm_sha256_file() {
  if _openllm_has_command shasum; then shasum -a 256 "$1" | cut -d' ' -f1
  elif _openllm_has_command sha256sum; then sha256sum "$1" | cut -d' ' -f1
  else _openllm_fail "shasum or sha256sum is required"; fi
}

_openllm_verify_self() {
  local source expected canonical actual count
  source="${BASH_SOURCE[0]:-}"
  # Piped (curl | bash): no file to re-read, so the byte self-check cannot run.
  # Integrity there = the immutable commit-pinned URL + the whole-script parse
  # guard (_openllm_main wraps everything, so a truncated download is a syntax
  # error and NOTHING executes). A real file gets the full check. Export an
  # EMPTY digest so `set -u` consumers (record_install_stamp) stay defined —
  # the stamp helper skips on a non-64-hex value, so piped installs simply
  # leave no drift stamp.
  if [ -z "$source" ] || [ ! -f "$source" ]; then
    readonly OPENLLM_SELF_SHA256=""
    export OPENLLM_SELF_SHA256
    return 0
  fi
  count="$(grep -c '^# openllm-self-sha256: ' "$source" || true)"
  [ "$count" = "1" ] || _openllm_fail "installer checksum field is invalid"
  expected="$(sed -n 's/^# openllm-self-sha256: \([0-9a-f]\{64\}\)$/\1/p' "$source")"
  [ "${#expected}" = "64" ] || _openllm_fail "installer checksum is invalid"
  umask 077
  canonical="$(mktemp "${TMPDIR:-/tmp}/openllm-self.XXXXXX")" || _openllm_fail "cannot create checksum file"
  trap 'rm -f "$canonical"' RETURN
  sed 's/^# openllm-self-sha256: [0-9a-f]\{64\}$/# openllm-self-sha256: __OPENLLM_SELF_SHA256__/' "$source" > "$canonical"
  actual="$(_openllm_sha256_file "$canonical")"
  [ "$actual" = "$expected" ] || _openllm_fail "installer checksum mismatch"
  rm -f "$canonical"
  trap - RETURN
  readonly OPENLLM_SELF_SHA256="$expected"
  export OPENLLM_SELF_SHA256
}

_openllm_verify_self

has_command() { command -v "$1" >/dev/null 2>&1; }
ensure_dir() { mkdir -p "$1"; }
copy_file() { [ -f "$1" ] && cp "$1" "$2"; }

sed_inplace() {
  local pattern="$1" replacement="$2" file="$3"
  if sed --version 2>/dev/null | grep -q GNU; then sed -i "s|${pattern}|${replacement}|g" "$file"
  else sed -i '' "s|${pattern}|${replacement}|g" "$file"; fi
}

safe_rmrf() {
  local target="$1" parent="$2"
  case "$target" in ""|"/"|"$HOME") _openllm_fail "refusing to remove $target" ;; esac
  case "/$target/" in *"/../"*) _openllm_fail "refusing path containing .." ;; esac
  case "$target" in "$parent"/*) ;; *) _openllm_fail "$target escapes $parent" ;; esac
  rm -rf "$target"
}

backup_once() {
  local src="$1" root="$HOME/.openllm/backups/$2" rel dest
  case "$src" in "$HOME"/*) rel="${src#"$HOME"/}" ;; *) rel="${src#/}" ;; esac
  dest="$root/$rel"
  [ ! -e "$dest" ] && [ ! -e "$dest.absent" ] || return 0
  (umask 077; mkdir -p "$(dirname "$dest")") 2>/dev/null || return 0
  if [ -f "$src" ]; then cp -p "$src" "$dest" 2>/dev/null && chmod 600 "$dest" 2>/dev/null || true
  else : > "$dest.absent" 2>/dev/null || true; fi
  chmod 700 "$HOME/.openllm/backups" "$root" 2>/dev/null || true
}

ensure_cli() {
  local display="$1" cmd="$2" dest_bin="$3" install_url="$4"
  if has_command "$cmd" || [ -x "$dest_bin" ]; then printf '  %s: already installed.\n' "$display"; return 0; fi
  if [ -n "${OPENLLM_SKIP_CLI_INSTALL:-}" ]; then
    printf '  %s: CLI not installed. Run its official installer first.\n' "$display" >&2
    return 1
  fi
  printf '  %s: installing the official CLI...\n' "$display"
  curl -fsSL "$install_url" | bash
  has_command "$cmd" || [ -x "$dest_bin" ] || _openllm_fail "$display install completed but its CLI was not found"
}

record_install_stamp() {
  local dir="$HOME/.openllm/installed" tmp
  # Piped installs export an empty digest (no file to self-hash) — skip the
  # stamp rather than writing a value drift comparison would misread.
  [[ "${OPENLLM_SELF_SHA256:-}" =~ ^[0-9a-f]{64}$ ]] || return 0
  (umask 077; mkdir -p "$dir") 2>/dev/null || return 0
  tmp="$dir/.setup-codex.$$"
  (umask 077; printf '%s' "$OPENLLM_SELF_SHA256" > "$tmp" && mv -f "$tmp" "$dir/setup-codex") 2>/dev/null || { rm -f "$tmp"; true; }
}
clear_install_stamp() {
  # Also clear legacy stamp names: tar-era route prefixes ("setups-"/"plugins-")
  # and the pre-fold "plugin"-area name.
  rm -f "$HOME/.openllm/installed/setup-codex" \
    "$HOME/.openllm/installed/setups-codex" \
    "$HOME/.openllm/installed/plugin-codex" \
    "$HOME/.openllm/installed/plugins-codex" 2>/dev/null || true
}
read_install_stamp() {
  local candidate value
  for candidate in "setup-codex" "setups-codex" "plugin-codex" "plugins-codex"; do
    [ -f "$HOME/.openllm/installed/$candidate" ] || continue
    value="$(cat "$HOME/.openllm/installed/$candidate" 2>/dev/null || true)"
    if [[ "$value" =~ ^[0-9a-f]{64}$ ]]; then printf '%s' "$value"; fi
    return 0
  done
}

OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-}"
GATEWAY_ORIGIN="$OPENLLM_CLOUD_ORIGIN"
API_KEY="${OPENLLM_API_KEY:-}"
OPENLLM_REGISTRY_REQUIRES_KEY="1"

_openllm_prepare_mode() {
  local mode="install" arg
  for arg in "$@"; do
    case "$arg" in
      -u) mode="uninstall" ;;
      -s) mode="state" ;;
    esac
  done
  if [ "$mode" = "install" ]; then
    [ -n "$OPENLLM_CLOUD_ORIGIN" ] || _openllm_fail "OPENLLM_CLOUD_ORIGIN is required"
    if [ "$OPENLLM_REGISTRY_REQUIRES_KEY" = "1" ]; then
      [ -n "$API_KEY" ] || _openllm_fail "OPENLLM_API_KEY is required"
    fi
  fi
}
_openllm_prepare_mode "$@"

materialize_registry_assets() { :; }

_openllm_main() {
# Configure the Codex CLI to route through OpenLLM — unified install / uninstall
# / state.
#
#   (no flag)  install: ensure the CLI + merge our managed regions into config.toml
#   -u         uninstall: strip the `# >>> openllm … <<<` managed regions + catalog
#   -s         state: print one JSON line {"installed":bool,"version":string|null}
#
# Run via `bash <file>` by the setup wrapper, which exports `$OPENLLM_CLOUD_ORIGIN` /
# `$API_KEY` and the `ensure_cli` / `ensure_dir` / `has_command` helpers. do_state
# is self-contained (no key, no inherited helpers).

CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
CONFIG_FILE="$CODEX_DIR/config.toml"
MODELS_FILE="$CODEX_DIR/openllm-models.json"

do_install() {
  # Ensure the Codex CLI is present before configuring it: reuse the existing
  # install if any, else run the official installer. (The daemon's isolated CLI is
  # just a symlink to this same binary — one install path, the non-isolated one.)
  ensure_cli "Codex" codex \
    "$HOME/.local/bin/codex" \
    "https://chatgpt.com/codex/install.sh"

  ensure_dir "$CODEX_DIR"

  # No custom header to inject: the local daemon authenticates with the SAME
  # `sk-llm` key Codex carries, and the gateway detects a live daemon from that
  # key's server-side activity — so it 307s subscription (chatgpt) hops to THIS
  # machine's daemon with no client header. See
  # `docs/proposals/daemon-control-via-neon-longpoll.md`.

  # Fetch a Codex model catalog generated from YOUR activated models (fallback
  # chains like `ultra`/`plus` + every connected provider model), keyed by slug
  # with real context-window metadata. Without it Codex can't find metadata for
  # our alias / non-OpenAI slugs and warns "Model metadata for <slug> not found.
  # Defaulting to fallback metadata; this can degrade performance and cause
  # issues" — then auto-compacts against a wrong 272k window. Authenticated with
  # your API key so it reflects your own chains. Best-effort: if the fetch fails
  # we skip the `model_catalog_json` line so the config stays valid (re-run to
  # pick it up).
  local catalog_line=""
  if curl -fsS -H "Authorization: Bearer ${API_KEY}" \
       "${OPENLLM_CLOUD_ORIGIN}/api/setup/codex/model-catalog" -o "$MODELS_FILE.tmp" 2>/dev/null; then
    mv "$MODELS_FILE.tmp" "$MODELS_FILE"
    catalog_line="model_catalog_json = \"${MODELS_FILE}\"
"
  else
    rm -f "$MODELS_FILE.tmp"
  fi

  # TOML requires top-level keys BEFORE any [table], so the provider-selection
  # keys and the provider table are two separate marked regions: the selection
  # is prepended (stays above every table), the table is appended.
  local TOP_BLOCK="# >>> openllm (managed) >>>
model_provider = \"openllm\"
model = \"ultra\"
${catalog_line}# <<< openllm (managed) <<<
"
  local TABLE_BLOCK="# >>> openllm provider (managed) >>>
[model_providers.openllm]
name = \"OpenLLM\"
base_url = \"${OPENLLM_CLOUD_ORIGIN}/v1\"
wire_api = \"responses\"
experimental_bearer_token = \"${API_KEY}\"
# <<< openllm provider (managed) <<<
"

  # Idempotent + TOML-safe merge. Strip any prior openllm-managed regions AND the
  # user's existing top-level model_provider/model (those before the first
  # [table]) so we never create duplicate keys; then PREPEND our selection block
  # and APPEND our provider table, preserving everything else.
  local cleaned
  # Write-once original backup (durable, kept forever) — distinct from the
  # per-run .openllm-bak rollback aid below, which is overwritten each install.
  if type backup_once >/dev/null 2>&1; then backup_once "$CONFIG_FILE" "setup/codex"; fi
  if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.openllm-bak"
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      /^[[:space:]]*\[/ { seen_table=1 }
      seen_table==0 && $0 ~ /^[[:space:]]*(model_provider|model)[[:space:]]*=/ { next }
      { print }
    ' "$CONFIG_FILE")
  else
    cleaned=""
  fi
  {
    printf '%s' "$TOP_BLOCK"
    [ -n "$cleaned" ] && printf '%s\n' "$cleaned"
    printf '%s' "$TABLE_BLOCK"
  } > "$CONFIG_FILE"

  echo "Codex configured."
  echo "  Provider: openllm → ${OPENLLM_CLOUD_ORIGIN}/v1 (wire_api=responses)"
  echo "  Config:   $CONFIG_FILE"
  echo "  Model:    ultra (default fallback chain)"
  echo "            Override per run with: codex -m <model>  (e.g. anthropic/claude-opus-4-8)"
  echo "            Codex's in-app /model picker only lists OpenAI models — use -m or edit"
  echo "            'model =' above to reach any OpenLLM catalog id / chain alias."
  if [ -n "$catalog_line" ]; then
    echo "  Catalog:  $MODELS_FILE (model_catalog_json — silences 'metadata not found')"
  else
    echo "  Catalog:  not fetched — Codex may warn 'model metadata not found'; re-run to add it."
  fi
  echo "  Daemon:   the chatgpt subscription runs on your local daemon —"
  echo "            start it + connect; the gateway routes to it via your API key."
}

do_uninstall() {
  # Best-effort + idempotent: strips the `# >>> openllm … <<<` managed regions
  # install wrote (the selection keys + the [model_providers.openllm] table) and
  # removes the fetched model catalog, leaving every other config.toml line
  # intact. No-op when the config is absent.
  if [ -f "$CONFIG_FILE" ]; then
    # Same region markers install emits — drop every openllm-managed block.
    local cleaned
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      { print }
    ' "$CONFIG_FILE")
    # Atomic replace: write to a temp file then mv over the config, so an
    # interrupted write can't corrupt/truncate config.toml.
    local tmp
    tmp=$(mktemp)
    if printf '%s\n' "$cleaned" > "$tmp" && mv "$tmp" "$CONFIG_FILE"; then
      echo "  Removed OpenLLM managed regions from $CONFIG_FILE"
    else
      rm -f "$tmp"
      echo "  Warning: failed to update $CONFIG_FILE — left untouched." >&2
      return 1
    fi
  else
    echo "  No config.toml found — nothing to undo."
  fi

  if [ -f "$MODELS_FILE" ]; then
    rm -f "$MODELS_FILE"
    echo "  Removed model catalog: $MODELS_FILE"
  fi

  echo "Codex OpenLLM configuration removed."
}

# Print one JSON line describing install state. Installed ⇔ our managed region
# marker is present in config.toml (the durable signal install writes). Exit 0
# always; the JSON IS the payload. No key, no network. (The `diverged` flag is
# injected by the gateway's state wrapper from the install-time version stamp.)
do_state() {
  local installed="false"
  if [ -f "$CONFIG_FILE" ] && grep -q "^# >>> openllm" "$CONFIG_FILE" 2>/dev/null; then
    installed="true"
  fi
  printf '{"installed":%s,"version":null,"installed_sha256":"%s"}\n' "$installed" "$(read_install_stamp)"
}

MODE="install"
TARGET="claude-code"
while [ $# -gt 0 ]; do
  case "$1" in
    -u) MODE="uninstall"; shift ;;
    -s) MODE="state"; shift ;;
    --target)
      [ $# -ge 2 ] || { echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2; }
      TARGET="$2"; shift 2 ;;
    *) echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2 ;;
  esac
done
[ "$TARGET" = "claude-code" ] || { echo "unsupported target: $TARGET" >&2; exit 2; }

case "$MODE" in
  install)   do_install; record_install_stamp ;;
  uninstall) do_uninstall; clear_install_stamp ;;
  state)     do_state ;;
esac
}
_openllm_main "$@"
