#!/usr/bin/env bash
# openllm-self-sha256: 5471cbe30600c0069acaf20ffd72ef9508b1e8c0079af3f947ea0f8a69b11ed6
# Generated by @openllm/registry. Edit the registry source, not this artifact.
set -euo pipefail

_openllm_fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
_openllm_has_command() { command -v "$1" >/dev/null 2>&1; }

_openllm_sha256_file() {
  if _openllm_has_command shasum; then shasum -a 256 "$1" | cut -d' ' -f1
  elif _openllm_has_command sha256sum; then sha256sum "$1" | cut -d' ' -f1
  else _openllm_fail "shasum or sha256sum is required"; fi
}

_openllm_verify_self() {
  local source expected canonical actual count
  source="${BASH_SOURCE[0]:-}"
  # Piped (curl | bash): no file to re-read, so the byte self-check cannot run.
  # Integrity there = the immutable commit-pinned URL + the whole-script parse
  # guard (_openllm_main wraps everything, so a truncated download is a syntax
  # error and NOTHING executes). A real file gets the full check. Export an
  # EMPTY digest so `set -u` consumers (record_install_stamp) stay defined —
  # the stamp helper skips on a non-64-hex value, so piped installs simply
  # leave no drift stamp.
  if [ -z "$source" ] || [ ! -f "$source" ]; then
    readonly OPENLLM_SELF_SHA256=""
    export OPENLLM_SELF_SHA256
    return 0
  fi
  count="$(grep -c '^# openllm-self-sha256: ' "$source" || true)"
  [ "$count" = "1" ] || _openllm_fail "installer checksum field is invalid"
  expected="$(sed -n 's/^# openllm-self-sha256: \([0-9a-f]\{64\}\)$/\1/p' "$source")"
  [ "${#expected}" = "64" ] || _openllm_fail "installer checksum is invalid"
  umask 077
  canonical="$(mktemp "${TMPDIR:-/tmp}/openllm-self.XXXXXX")" || _openllm_fail "cannot create checksum file"
  trap 'rm -f "$canonical"' RETURN
  sed 's/^# openllm-self-sha256: [0-9a-f]\{64\}$/# openllm-self-sha256: __OPENLLM_SELF_SHA256__/' "$source" > "$canonical"
  actual="$(_openllm_sha256_file "$canonical")"
  [ "$actual" = "$expected" ] || _openllm_fail "installer checksum mismatch"
  rm -f "$canonical"
  trap - RETURN
  readonly OPENLLM_SELF_SHA256="$expected"
  export OPENLLM_SELF_SHA256
}

_openllm_verify_self

has_command() { command -v "$1" >/dev/null 2>&1; }
ensure_dir() { mkdir -p "$1"; }
copy_file() { [ -f "$1" ] && cp "$1" "$2"; }

sed_inplace() {
  local pattern="$1" replacement="$2" file="$3"
  if sed --version 2>/dev/null | grep -q GNU; then sed -i "s|${pattern}|${replacement}|g" "$file"
  else sed -i '' "s|${pattern}|${replacement}|g" "$file"; fi
}

safe_rmrf() {
  local target="$1" parent="$2"
  case "$target" in ""|"/"|"$HOME") _openllm_fail "refusing to remove $target" ;; esac
  case "/$target/" in *"/../"*) _openllm_fail "refusing path containing .." ;; esac
  case "$target" in "$parent"/*) ;; *) _openllm_fail "$target escapes $parent" ;; esac
  rm -rf "$target"
}

backup_once() {
  local src="$1" root="$HOME/.openllm/backups/$2" rel dest
  case "$src" in "$HOME"/*) rel="${src#"$HOME"/}" ;; *) rel="${src#/}" ;; esac
  dest="$root/$rel"
  [ ! -e "$dest" ] && [ ! -e "$dest.absent" ] || return 0
  (umask 077; mkdir -p "$(dirname "$dest")") 2>/dev/null || return 0
  if [ -f "$src" ]; then cp -p "$src" "$dest" 2>/dev/null && chmod 600 "$dest" 2>/dev/null || true
  else : > "$dest.absent" 2>/dev/null || true; fi
  chmod 700 "$HOME/.openllm/backups" "$root" 2>/dev/null || true
}

ensure_cli() {
  local display="$1" cmd="$2" dest_bin="$3" install_url="$4"
  if has_command "$cmd" || [ -x "$dest_bin" ]; then printf '  %s: already installed.\n' "$display"; return 0; fi
  if [ -n "${OPENLLM_SKIP_CLI_INSTALL:-}" ]; then
    printf '  %s: CLI not installed. Run its official installer first.\n' "$display" >&2
    return 1
  fi
  printf '  %s: installing the official CLI...\n' "$display"
  curl -fsSL "$install_url" | bash
  has_command "$cmd" || [ -x "$dest_bin" ] || _openllm_fail "$display install completed but its CLI was not found"
}

record_install_stamp() {
  local dir="$HOME/.openllm/installed" tmp
  # Piped installs export an empty digest (no file to self-hash) — skip the
  # stamp rather than writing a value drift comparison would misread.
  [[ "${OPENLLM_SELF_SHA256:-}" =~ ^[0-9a-f]{64}$ ]] || return 0
  (umask 077; mkdir -p "$dir") 2>/dev/null || return 0
  tmp="$dir/.setup-kimi-code.$$"
  (umask 077; printf '%s' "$OPENLLM_SELF_SHA256" > "$tmp" && mv -f "$tmp" "$dir/setup-kimi-code") 2>/dev/null || { rm -f "$tmp"; true; }
  # Human-facing catalog version installed alongside the digest stamp — read by
  # the state probe so the dashboard can show "installed vX · published vY".
  tmp="$dir/.setup-kimi-code.version.$$"
  (umask 077; printf '%s' "1.0.1" > "$tmp" && mv -f "$tmp" "$dir/setup-kimi-code.version") 2>/dev/null || { rm -f "$tmp"; true; }
}
clear_install_stamp() {
  # Also clear legacy stamp names: tar-era route prefixes ("setups-"/"plugins-")
  # and the pre-fold "plugin"-area name.
  rm -f "$HOME/.openllm/installed/setup-kimi-code" \
    "$HOME/.openllm/installed/setup-kimi-code.version" \
    "$HOME/.openllm/installed/setups-kimi-code" \
    "$HOME/.openllm/installed/plugin-kimi-code" \
    "$HOME/.openllm/installed/plugins-kimi-code" 2>/dev/null || true
}
read_install_stamp() {
  local candidate value
  for candidate in "setup-kimi-code" "setups-kimi-code" "plugin-kimi-code" "plugins-kimi-code"; do
    [ -f "$HOME/.openllm/installed/$candidate" ] || continue
    value="$(cat "$HOME/.openllm/installed/$candidate" 2>/dev/null || true)"
    if [[ "$value" =~ ^[0-9a-f]{64}$ ]]; then printf '%s' "$value"; fi
    return 0
  done
}
read_install_version() {
  local value
  value="$(cat "$HOME/.openllm/installed/setup-kimi-code.version" 2>/dev/null || true)"
  case "$value" in *[!0-9a-zA-Z.-]*|'') return 0 ;; esac
  printf '%s' "$value"
}

OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-}"
GATEWAY_ORIGIN="$OPENLLM_CLOUD_ORIGIN"
API_KEY="${OPENLLM_API_KEY:-}"
OPENLLM_REGISTRY_REQUIRES_KEY="1"

_openllm_prepare_mode() {
  local mode="install" arg
  for arg in "$@"; do
    case "$arg" in
      -u) mode="uninstall" ;;
      -s) mode="state" ;;
    esac
  done
  if [ "$mode" = "install" ]; then
    [ -n "$OPENLLM_CLOUD_ORIGIN" ] || _openllm_fail "OPENLLM_CLOUD_ORIGIN is required"
    if [ "$OPENLLM_REGISTRY_REQUIRES_KEY" = "1" ]; then
      [ -n "$API_KEY" ] || _openllm_fail "OPENLLM_API_KEY is required"
    fi
  fi
}
_openllm_prepare_mode "$@"

materialize_registry_assets() { :; }

_openllm_main() {
# Configure the Kimi CLI to route through OpenLLM — unified install / uninstall
# / state.
#
#   (no flag)  install: ensure the CLI + merge our managed regions into config.toml
#   -u         uninstall: strip the `# >>> openllm … <<<` managed regions
#   -s         state: print one JSON line {"installed":bool,"version":string|null}
#
# Run via `bash <file>` by the setup wrapper, which exports `$OPENLLM_CLOUD_ORIGIN` /
# `$API_KEY` and the `ensure_cli` / `ensure_dir` / `has_command` helpers. do_state
# is self-contained (no key, no inherited helpers).

KIMI_DIR="${KIMI_CODE_HOME:-$HOME/.kimi-code}"
CONFIG_FILE="$KIMI_DIR/config.toml"

do_install() {
  # Ensure the Kimi CLI is present before configuring it: reuse the existing
  # install if any, else run the official installer. (The daemon's isolated CLI is
  # just a symlink to this same binary — one install path, the non-isolated one.)
  ensure_cli "Kimi CLI" kimi \
    "$HOME/.kimi-code/bin/kimi" \
    "https://code.kimi.com/kimi-code/install.sh"

  ensure_dir "$KIMI_DIR"

  # No custom header to inject: the local daemon authenticates with the SAME
  # `sk-llm` key Kimi carries, and the gateway detects a live daemon from that
  # key's server-side activity — so it 307s subscription (kimi_code) hops to
  # THIS machine's daemon with no client header. See
  # `docs/proposals/daemon-control-via-neon-longpoll.md`.

  local DEFAULT_MODEL="ultra"

  # The Kimi CLI REQUIRES an explicit [models."<name>"] entry for every model it
  # routes to — `default_model = "ultra"` with no [models."ultra"] hard-fails:
  #   [config.invalid] Model "ultra" is not configured ... Add a [models."ultra"]
  #   entry with max_context_size.
  # Fetch a TOML block of [models.*] tables for YOUR activated models (fallback
  # chains + connected provider models), each with its real max_context_size.
  # Authenticated with your API key so it reflects your own chains.
  local models_block=""
  local models_tmp
  models_tmp=$(mktemp)
  if curl -fsS -H "Authorization: Bearer ${API_KEY}" \
       "${OPENLLM_CLOUD_ORIGIN}/api/setup/kimi-code/model-catalog" -o "$models_tmp" 2>/dev/null \
       && [ -s "$models_tmp" ]; then
    models_block=$(cat "$models_tmp")
  fi
  rm -f "$models_tmp"

  # Guarantee the default model is always defined, even if the fetch failed or
  # didn't include it — otherwise the CLI won't start.
  case "$models_block" in
    *"[models.\"${DEFAULT_MODEL}\"]"*) : ;;
    *) models_block="${models_block:+${models_block}

}[models.\"${DEFAULT_MODEL}\"]
provider = \"openllm\"
model = \"${DEFAULT_MODEL}\"
max_context_size = 262144" ;;
  esac

  # Our managed blocks. TOML requires top-level keys BEFORE any [table], so the
  # provider-selection keys and the provider table are two separate marked
  # regions: the selection is prepended (stays above every table), the tables
  # (provider + per-model) are appended (self-contained tables are always valid
  # at the end).
  local TOP_BLOCK="# >>> openllm (managed) >>>
default_provider = \"openllm\"
default_model = \"${DEFAULT_MODEL}\"
# <<< openllm (managed) <<<
"
  local TABLE_BLOCK="# >>> openllm provider (managed) >>>
[providers.openllm]
type = \"openai_legacy\"
base_url = \"${OPENLLM_CLOUD_ORIGIN}/v1\"
api_key = \"${API_KEY}\"
${models_block}
# <<< openllm provider (managed) <<<
"

  # Idempotent + TOML-safe merge. Strip any prior openllm-managed regions AND the
  # user's existing top-level default_provider/default_model (those before the
  # first [table]) so we never create duplicate keys; then PREPEND our selection
  # block and APPEND our provider table, preserving everything else.
  local cleaned
  # Write-once original backup (durable, kept forever) — distinct from the
  # per-run .openllm-bak rollback aid below, which is overwritten each install.
  if type backup_once >/dev/null 2>&1; then backup_once "$CONFIG_FILE" "setup/kimi-code"; fi
  if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.openllm-bak"
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      /^[[:space:]]*\[/ { seen_table=1 }
      seen_table==0 && $0 ~ /^[[:space:]]*(default_provider|default_model)[[:space:]]*=/ { next }
      { print }
    ' "$CONFIG_FILE")
  else
    cleaned=""
  fi
  {
    printf '%s' "$TOP_BLOCK"
    [ -n "$cleaned" ] && printf '%s\n' "$cleaned"
    printf '%s' "$TABLE_BLOCK"
  } > "$CONFIG_FILE"

  local model_count
  model_count=$(printf '%s\n' "$models_block" | grep -c '^\[models\.' 2>/dev/null || printf '0')
  echo "Kimi CLI configured."
  echo "  Provider: openllm → ${OPENLLM_CLOUD_ORIGIN}/v1 (type=openai_legacy)"
  echo "  Config:   $CONFIG_FILE"
  echo "  Model:    ${DEFAULT_MODEL} (default) · ${model_count} [models.*] entries written"
  echo "            Switch models in-session with /model, or set default_model above."
  echo "  Daemon:   the kimi_code subscription runs on your local daemon —"
  echo "            start it + connect; the gateway routes to it via your API key."
}

do_uninstall() {
  # Best-effort + idempotent: strips the `# >>> openllm … <<<` managed regions
  # install wrote (the selection keys + the [providers.openllm] / per-model
  # tables), leaving every other config.toml line intact. No-op when the config
  # is absent.
  if [ -f "$CONFIG_FILE" ]; then
    # Same region markers install emits — drop every openllm-managed block.
    local cleaned
    cleaned=$(awk '
      /^# >>> openllm/ { skip=1 }
      skip==1 { if ($0 ~ /^# <<< openllm/) skip=0; next }
      { print }
    ' "$CONFIG_FILE")
    # Atomic replace: write to a temp file then mv over the config, so an
    # interrupted write can't corrupt/truncate config.toml.
    local tmp
    tmp=$(mktemp)
    if printf '%s\n' "$cleaned" > "$tmp" && mv "$tmp" "$CONFIG_FILE"; then
      echo "  Removed OpenLLM managed regions from $CONFIG_FILE"
    else
      rm -f "$tmp"
      echo "  Warning: failed to update $CONFIG_FILE — left untouched." >&2
      return 1
    fi
  else
    echo "  No config.toml found — nothing to undo."
  fi

  echo "Kimi CLI OpenLLM configuration removed."
}

# Print one JSON line describing install state. Installed ⇔ our managed region
# marker is present in config.toml (the durable signal install writes). Exit 0
# always; the JSON IS the payload. No key, no network. (The `diverged` flag is
# injected by the gateway's state wrapper from the install-time version stamp.)
do_state() {
  local installed="false"
  if [ -f "$CONFIG_FILE" ] && grep -q "^# >>> openllm" "$CONFIG_FILE" 2>/dev/null; then
    installed="true"
  fi
  version="null"
  iv="$(read_install_version)"
  [ -n "$iv" ] && version="\"$iv\""
  printf '{"installed":%s,"version":%s,"installed_sha256":"%s"}\n' "$installed" "$version" "$(read_install_stamp)"
}

MODE="install"
TARGET="claude-code"
while [ $# -gt 0 ]; do
  case "$1" in
    -u) MODE="uninstall"; shift ;;
    -s) MODE="state"; shift ;;
    --target)
      [ $# -ge 2 ] || { echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2; }
      TARGET="$2"; shift 2 ;;
    *) echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2 ;;
  esac
done
[ "$TARGET" = "claude-code" ] || { echo "unsupported target: $TARGET" >&2; exit 2; }

case "$MODE" in
  install)   do_install; record_install_stamp ;;
  uninstall) do_uninstall; clear_install_stamp ;;
  state)     do_state ;;
esac
}
_openllm_main "$@"
