#!/usr/bin/env bash
# openllm-self-sha256: 7c57f68b9651cbaad108a30313ac1d6d2f39f31f6e285943a9d61f336f5c83c9
# Generated by @openllm/registry. Edit the registry source, not this artifact.
set -euo pipefail

_openllm_fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
_openllm_has_command() { command -v "$1" >/dev/null 2>&1; }

_openllm_sha256_file() {
  if _openllm_has_command shasum; then shasum -a 256 "$1" | cut -d' ' -f1
  elif _openllm_has_command sha256sum; then sha256sum "$1" | cut -d' ' -f1
  else _openllm_fail "shasum or sha256sum is required"; fi
}

_openllm_verify_self() {
  local source expected canonical actual count
  source="${BASH_SOURCE[0]:-}"
  # Piped (curl | bash): no file to re-read, so the byte self-check cannot run.
  # Integrity there = the immutable commit-pinned URL + the whole-script parse
  # guard (_openllm_main wraps everything, so a truncated download is a syntax
  # error and NOTHING executes). A real file gets the full check. Export an
  # EMPTY digest so `set -u` consumers (record_install_stamp) stay defined —
  # the stamp helper skips on a non-64-hex value, so piped installs simply
  # leave no drift stamp.
  if [ -z "$source" ] || [ ! -f "$source" ]; then
    readonly OPENLLM_SELF_SHA256=""
    export OPENLLM_SELF_SHA256
    return 0
  fi
  count="$(grep -c '^# openllm-self-sha256: ' "$source" || true)"
  [ "$count" = "1" ] || _openllm_fail "installer checksum field is invalid"
  expected="$(sed -n 's/^# openllm-self-sha256: \([0-9a-f]\{64\}\)$/\1/p' "$source")"
  [ "${#expected}" = "64" ] || _openllm_fail "installer checksum is invalid"
  umask 077
  canonical="$(mktemp "${TMPDIR:-/tmp}/openllm-self.XXXXXX")" || _openllm_fail "cannot create checksum file"
  trap 'rm -f "$canonical"' RETURN
  sed 's/^# openllm-self-sha256: [0-9a-f]\{64\}$/# openllm-self-sha256: __OPENLLM_SELF_SHA256__/' "$source" > "$canonical"
  actual="$(_openllm_sha256_file "$canonical")"
  [ "$actual" = "$expected" ] || _openllm_fail "installer checksum mismatch"
  rm -f "$canonical"
  trap - RETURN
  readonly OPENLLM_SELF_SHA256="$expected"
  export OPENLLM_SELF_SHA256
}

_openllm_verify_self

has_command() { command -v "$1" >/dev/null 2>&1; }
ensure_dir() { mkdir -p "$1"; }
copy_file() { [ -f "$1" ] && cp "$1" "$2"; }

sed_inplace() {
  local pattern="$1" replacement="$2" file="$3"
  if sed --version 2>/dev/null | grep -q GNU; then sed -i "s|${pattern}|${replacement}|g" "$file"
  else sed -i '' "s|${pattern}|${replacement}|g" "$file"; fi
}

safe_rmrf() {
  local target="$1" parent="$2"
  case "$target" in ""|"/"|"$HOME") _openllm_fail "refusing to remove $target" ;; esac
  case "/$target/" in *"/../"*) _openllm_fail "refusing path containing .." ;; esac
  case "$target" in "$parent"/*) ;; *) _openllm_fail "$target escapes $parent" ;; esac
  rm -rf "$target"
}

backup_once() {
  local src="$1" root="$HOME/.openllm/backups/$2" rel dest
  case "$src" in "$HOME"/*) rel="${src#"$HOME"/}" ;; *) rel="${src#/}" ;; esac
  dest="$root/$rel"
  [ ! -e "$dest" ] && [ ! -e "$dest.absent" ] || return 0
  (umask 077; mkdir -p "$(dirname "$dest")") 2>/dev/null || return 0
  if [ -f "$src" ]; then cp -p "$src" "$dest" 2>/dev/null && chmod 600 "$dest" 2>/dev/null || true
  else : > "$dest.absent" 2>/dev/null || true; fi
  chmod 700 "$HOME/.openllm/backups" "$root" 2>/dev/null || true
}

ensure_cli() {
  local display="$1" cmd="$2" dest_bin="$3" install_url="$4"
  if has_command "$cmd" || [ -x "$dest_bin" ]; then printf '  %s: already installed.\n' "$display"; return 0; fi
  if [ -n "${OPENLLM_SKIP_CLI_INSTALL:-}" ]; then
    printf '  %s: CLI not installed. Run its official installer first.\n' "$display" >&2
    return 1
  fi
  printf '  %s: installing the official CLI...\n' "$display"
  curl -fsSL "$install_url" | bash
  has_command "$cmd" || [ -x "$dest_bin" ] || _openllm_fail "$display install completed but its CLI was not found"
}

record_install_stamp() {
  local dir="$HOME/.openllm/installed" tmp
  # Piped installs export an empty digest (no file to self-hash) — skip the
  # stamp rather than writing a value drift comparison would misread.
  [[ "${OPENLLM_SELF_SHA256:-}" =~ ^[0-9a-f]{64}$ ]] || return 0
  (umask 077; mkdir -p "$dir") 2>/dev/null || return 0
  tmp="$dir/.setup-raycast.$$"
  (umask 077; printf '%s' "$OPENLLM_SELF_SHA256" > "$tmp" && mv -f "$tmp" "$dir/setup-raycast") 2>/dev/null || { rm -f "$tmp"; true; }
  # Human-facing catalog version installed alongside the digest stamp — read by
  # the state probe so the dashboard can show "installed vX · published vY".
  tmp="$dir/.setup-raycast.version.$$"
  (umask 077; printf '%s' "1.6.39-registry.7" > "$tmp" && mv -f "$tmp" "$dir/setup-raycast.version") 2>/dev/null || { rm -f "$tmp"; true; }
}
clear_install_stamp() {
  # Also clear legacy stamp names: tar-era route prefixes ("setups-"/"plugins-")
  # and the pre-fold "plugin"-area name.
  rm -f "$HOME/.openllm/installed/setup-raycast" \
    "$HOME/.openllm/installed/setup-raycast.version" \
    "$HOME/.openllm/installed/setups-raycast" \
    "$HOME/.openllm/installed/plugin-raycast" \
    "$HOME/.openllm/installed/plugins-raycast" 2>/dev/null || true
}
read_install_stamp() {
  local candidate value
  for candidate in "setup-raycast" "setups-raycast" "plugin-raycast" "plugins-raycast"; do
    [ -f "$HOME/.openllm/installed/$candidate" ] || continue
    value="$(cat "$HOME/.openllm/installed/$candidate" 2>/dev/null || true)"
    if [[ "$value" =~ ^[0-9a-f]{64}$ ]]; then printf '%s' "$value"; fi
    return 0
  done
}
read_install_version() {
  local value
  value="$(cat "$HOME/.openllm/installed/setup-raycast.version" 2>/dev/null || true)"
  case "$value" in *[!0-9a-zA-Z.-]*|'') return 0 ;; esac
  printf '%s' "$value"
}

OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-}"
GATEWAY_ORIGIN="$OPENLLM_CLOUD_ORIGIN"
API_KEY="${OPENLLM_API_KEY:-}"
OPENLLM_REGISTRY_REQUIRES_KEY="1"

_openllm_prepare_mode() {
  local mode="install" arg
  for arg in "$@"; do
    case "$arg" in
      -u) mode="uninstall" ;;
      -s) mode="state" ;;
    esac
  done
  if [ "$mode" = "install" ]; then
    [ -n "$OPENLLM_CLOUD_ORIGIN" ] || _openllm_fail "OPENLLM_CLOUD_ORIGIN is required"
    if [ "$OPENLLM_REGISTRY_REQUIRES_KEY" = "1" ]; then
      [ -n "$API_KEY" ] || _openllm_fail "OPENLLM_API_KEY is required"
    fi
  fi
}
_openllm_prepare_mode "$@"

materialize_registry_assets() { :; }

_openllm_main() {
# Configure Raycast AI to use OpenLLM — unified install / uninstall / state.
#
#   (no flag)  install: merge an `openllm` custom provider into providers.yaml
#   -u         uninstall: strip ONLY the `# >>> openllm … <<<` managed region
#   -s         state: print one JSON line {"installed":bool,"version":string|null}
#
# Run via `bash <file>` by the setup wrapper, which exports `$OPENLLM_CLOUD_ORIGIN` /
# `$API_KEY` and the `ensure_dir` / `has_command` helpers. do_state is
# self-contained (no key, no inherited helpers).
#
# Raycast's custom-provider feature reads a `providers.yaml`. There is no
# guaranteed hot-reload — the user restarts Raycast after install. We merge with
# awk (no YAML library needed — system python3 ships no PyYAML) using the same
# comment-delimited managed region as the codex/kimi setups.

# Raycast's config dir on macOS. `RAYCAST_PROVIDERS_FILE` overrides it for users
# whose "Reveal Providers Config" points elsewhere.
RAYCAST_DIR="${RAYCAST_CONFIG_DIR:-$HOME/.config/raycast}"
CONFIG_FILE="${RAYCAST_PROVIDERS_FILE:-$RAYCAST_DIR/ai/providers.yaml}"

BEGIN_MARK="# >>> openllm (managed) >>>"
END_MARK="# <<< openllm (managed) <<<"

# Emit a value as a YAML double-quoted scalar so YAML-special characters in
# $OPENLLM_CLOUD_ORIGIN / $API_KEY (`:`, `#`, `{`, a leading `@`/`*`/`&`, …) can never
# break the document. Escapes `\` then `"` — the only two chars that need it
# inside a double-quoted YAML scalar.
yaml_dq() {
  local v="$1"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  printf '"%s"' "$v"
}

# A minimal, valid fallback models block (the three fallback-chain aliases) used
# only when the gateway's per-user catalog fetch fails — Raycast requires >= 1
# model, so the provider must never be emitted model-less.
fallback_models_block() {
  cat <<'YAMLEOF'
      - id: "ultra"
        name: "Ultra"
        context: 200000
        abilities:
          temperature:
            supported: true
          vision:
            supported: true
          system_message:
            supported: true
          tools:
            supported: true
          reasoning_effort:
            supported: true
      - id: "plus"
        name: "Plus"
        context: 200000
        abilities:
          temperature:
            supported: true
          vision:
            supported: true
          system_message:
            supported: true
          tools:
            supported: true
          reasoning_effort:
            supported: true
      - id: "lite"
        name: "Lite"
        context: 128000
        abilities:
          temperature:
            supported: true
          vision:
            supported: true
          system_message:
            supported: true
          tools:
            supported: true
          reasoning_effort:
            supported: true
YAMLEOF
}

do_install() {
  ensure_dir "$(dirname "$CONFIG_FILE")"

  # Write-once original backup (durable, kept even on uninstall — unlike the
  # per-run .openllm-bak below). On a box that installed BEFORE this shipped,
  # the first backup taken may already contain our managed region (with the
  # key) — hence backup_once's 600/700 perms. The .absent marker records a
  # fresh-write install (no pre-existing providers.yaml).
  if type backup_once >/dev/null 2>&1; then backup_once "$CONFIG_FILE" "setup/raycast"; fi

  # Fetch a Raycast models block generated from YOUR activated models (fallback
  # chains + every connected provider model), each with its real context window
  # and abilities. Authenticated with your API key so it reflects your own
  # chains. Best-effort: if the fetch fails or is empty we fall back to the
  # ultra/plus/lite aliases so the provider always has the >= 1 model Raycast
  # requires.
  local models_block="" tmp_models
  tmp_models="$(mktemp)"
  if curl -fsS -H "Authorization: Bearer ${API_KEY}" \
       "${OPENLLM_CLOUD_ORIGIN}/api/setup/raycast/model-catalog" -o "$tmp_models" 2>/dev/null \
     && [ -s "$tmp_models" ]; then
    models_block="$(cat "$tmp_models")"
  fi
  rm -f "$tmp_models"
  if [ -z "$models_block" ]; then
    models_block="$(fallback_models_block)"
    echo "  Catalog: not fetched — using ultra/plus/lite fallback. Re-run to pull your full model list."
  fi

  # Assemble our managed provider entry (a single list item under `providers:`).
  # One `api_keys.default` bearer credential; no per-model `provider:` routing
  # needed. `base_url` ends in /v1 — Raycast appends /chat/completions itself.
  # base_url + the key are DOUBLE-QUOTED (via yaml_dq) so a value carrying a
  # YAML-special char (`:`, `#`, `{`, a leading `@`, …) can't break the document.
  local block_file
  block_file="$(mktemp)"
  {
    echo "$BEGIN_MARK"
    echo "  - id: openllm"
    echo "    name: OpenLLM"
    echo "    base_url: $(yaml_dq "${OPENLLM_CLOUD_ORIGIN}/v1")"
    echo "    api_keys:"
    echo "      default: $(yaml_dq "${API_KEY}")"
    echo "    models:"
    printf '%s\n' "$models_block"
    echo "$END_MARK"
  } > "$block_file"

  if [ ! -f "$CONFIG_FILE" ]; then
    # No existing config — write a fresh providers.yaml with just our block.
    {
      echo "providers:"
      cat "$block_file"
    } > "$CONFIG_FILE"
    rm -f "$block_file"
    echo "Raycast configured (new providers.yaml written)."
    print_summary
    return 0
  fi

  # Back up before touching an existing file.
  cp "$CONFIG_FILE" "$CONFIG_FILE.openllm-bak"

  # 1) Strip any prior openllm-managed region so re-runs never duplicate it.
  local cleaned
  cleaned="$(awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    index($0, b) == 1 { skip = 1; next }
    skip == 1 { if (index($0, e) == 1) skip = 0; next }
    { print }
  ' "$CONFIG_FILE")"

  # 2) Insert our block. Match the FIRST top-level `providers:` line — with or
  #    without an inline value (`providers:`, `providers: []`, `providers: {}`,
  #    `providers:  # comment`) — rewrite that line to a canonical block-form
  #    `providers:` (dropping only an inline `[]`/`{}` sequence value; a trailing
  #    comment goes too) and insert our entry as its FIRST child. Block-form
  #    children that already followed are preserved (they stay indented after our
  #    block). awk writes a sentinel to a side file when it inserts so we can tell
  #    an in-place insert from the no-key case WITHOUT re-parsing. If there is no
  #    top-level `providers:` key at all, append a canonical section. Either way
  #    the block ends up present — the grep guard below rejects a silent skip.
  local merged sentinel
  sentinel="$(mktemp)"
  merged="$(printf '%s\n' "$cleaned" | awk -v blk="$block_file" -v sf="$sentinel" '
    BEGIN { done = 0 }
    done == 0 && /^providers:([[:space:]].*)?$/ {
      print "providers:"
      while ((getline line < blk) > 0) print line
      done = 1
      print "1" > sf
      next
    }
    { print }
  ')"
  if [ ! -s "$sentinel" ]; then
    # No top-level providers: key was found — append a canonical section.
    merged="$(printf '%s\nproviders:\n%s' "$merged" "$(cat "$block_file")")"
  fi
  rm -f "$sentinel" "$block_file"

  # Atomic replace so an interrupted write can't corrupt providers.yaml.
  local tmp
  tmp="$(mktemp)"
  # Guard against a silent skip: the managed block MUST be present in the result
  # before we claim success. `printf | grep` verifies it, then the atomic mv
  # lands it — we only print "Raycast configured." after both.
  if ! printf '%s\n' "$merged" | grep -qF "$BEGIN_MARK"; then
    rm -f "$tmp"
    echo "Error: failed to insert the openllm provider into $CONFIG_FILE — left untouched." >&2
    cp "$CONFIG_FILE.openllm-bak" "$CONFIG_FILE"
    exit 1
  fi
  if printf '%s\n' "$merged" > "$tmp" && mv "$tmp" "$CONFIG_FILE"; then
    echo "Raycast configured."
  else
    rm -f "$tmp"
    echo "Error: failed to update $CONFIG_FILE — restoring backup." >&2
    cp "$CONFIG_FILE.openllm-bak" "$CONFIG_FILE"
    exit 1
  fi
  print_summary
}

print_summary() {
  echo "  Provider: openllm → ${OPENLLM_CLOUD_ORIGIN}/v1 (OpenAI chat-completions)"
  echo "  Config:   $CONFIG_FILE"
  echo "  Backup:   $CONFIG_FILE.openllm-bak (if it existed)"
  echo "  Next:     enable Settings → AI → Custom Providers, then RESTART Raycast"
  echo "            (it doesn't reliably hot-reload). Use 'Manage Models' to enable them."
  echo "  Daemon:   subscription models (claude_code/chatgpt/kimi_code) run on your"
  echo "            local daemon — start it + connect; the gateway routes via your key."
}

do_uninstall() {
  # Best-effort + idempotent: strips the `# >>> openllm … <<<` managed region
  # install wrote, leaving every other provider intact. No-op when absent.
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "  No providers.yaml found — nothing to undo."
    echo "Raycast OpenLLM configuration removed."
    return 0
  fi
  local cleaned tmp
  cleaned="$(awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    index($0, b) == 1 { skip = 1; next }
    skip == 1 { if (index($0, e) == 1) skip = 0; next }
    { print }
  ' "$CONFIG_FILE")"
  # Normalize a now-childless `providers:` back to install-parity: when removing
  # our block leaves a bare `providers:` key with NO list items following it, a
  # YAML load reads it as null (a schema drift from what install wrote). Rewrite
  # it to an explicit empty sequence `providers: []` so the file stays valid +
  # matches the shape install produces. A `providers:` still followed by other
  # entries is left as block form (untouched).
  cleaned="$(printf '%s\n' "$cleaned" | awk '
    { lines[NR] = $0 }
    END {
      for (i = 1; i <= NR; i++) {
        if (lines[i] ~ /^providers:[[:space:]]*$/) {
          has_child = 0
          for (j = i + 1; j <= NR; j++) {
            if (lines[j] ~ /^[[:space:]]*$/) continue        # blank
            if (lines[j] ~ /^[[:space:]]*#/) continue        # comment
            if (lines[j] ~ /^[[:space:]]+/) { has_child = 1 } # indented → a child
            break
          }
          if (has_child == 0) { print "providers: []"; continue }
        }
        print lines[i]
      }
    }
  ')"
  tmp="$(mktemp)"
  if printf '%s\n' "$cleaned" > "$tmp" && mv "$tmp" "$CONFIG_FILE"; then
    echo "  Removed OpenLLM managed region from $CONFIG_FILE"
  else
    rm -f "$tmp"
    echo "  Warning: failed to update $CONFIG_FILE — left untouched." >&2
    return 1
  fi
  # Scrub the install-time backup: it holds a verbatim copy of a providers.yaml
  # that (on any re-install) already contained our `api_keys.default` bearer
  # token, and uninstall is exactly when that secret-at-rest should go. Best
  # effort — absent on a first-ever install (nothing to back up).
  if [ -f "$CONFIG_FILE.openllm-bak" ]; then
    rm -f "$CONFIG_FILE.openllm-bak"
    echo "  Removed backup $CONFIG_FILE.openllm-bak (held the API key)."
  fi
  echo "Raycast OpenLLM configuration removed."
  echo "  Restart Raycast for the change to take effect."
}

# Print one JSON line describing install state. Installed ⇔ our managed region
# marker is present in providers.yaml. Exit 0 always; the JSON IS the payload.
# No key, no network. Self-contained (no inherited helpers). (The `diverged`
# flag is injected by the gateway's state wrapper from the install-time
# version stamp.)
do_state() {
  local file="${RAYCAST_PROVIDERS_FILE:-${RAYCAST_CONFIG_DIR:-$HOME/.config/raycast}/ai/providers.yaml}"
  local installed="false"
  if [ -f "$file" ] && grep -q "^# >>> openllm" "$file" 2>/dev/null; then
    installed="true"
  fi
  version="null"
  iv="$(read_install_version)"
  [ -n "$iv" ] && version="\"$iv\""
  printf '{"installed":%s,"version":%s,"installed_sha256":"%s"}\n' "$installed" "$version" "$(read_install_stamp)"
}

MODE="install"
TARGET="claude-code"
while [ $# -gt 0 ]; do
  case "$1" in
    -u) MODE="uninstall"; shift ;;
    -s) MODE="state"; shift ;;
    --target)
      [ $# -ge 2 ] || { echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2; }
      TARGET="$2"; shift 2 ;;
    *) echo "usage: install.sh [-u|-s] [--target claude-code]" >&2; exit 2 ;;
  esac
done
[ "$TARGET" = "claude-code" ] || { echo "unsupported target: $TARGET" >&2; exit 2; }

case "$MODE" in
  install)   do_install; record_install_stamp ;;
  uninstall) do_uninstall; clear_install_stamp ;;
  state)     do_state ;;
esac
}
_openllm_main "$@"
